/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Sep 18 2023
 * Processor: STM32F401CB
 * Compiler:  GCC for ARM
 */

#include <stm32f4xx.h>

int main(void)
{
	// Write your code here
	while (1);

	return 0;
}
