# Project Name
TARGET = VSCode

# Sources
CPP_SOURCES = VSCode.cpp

# Library Locations
LIBDAISY_DIR = ../Projects/WorkingFiles/DaisyExamples/libDaisy/
DAISYSP_DIR = ../Projects/WorkingFiles/DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
